### ISSUE TITLE
what if: menu subcribes to buttons

### ISSUE THREAD

**Issue by ahdinosaur** [peachcloud/peach-buttons#1]
hi @mycognosist, this is rad :sunny:

i'm wondering, rather than the buttons service calling methods on the menu service, which means the buttons service is tightly linked to the menu service, what if: the menu service subscribed to the buttons service, so the menu received an event every time a button was pushed and therefore in the menu logic we decide how to handle buttons.

i think this would make the buttons service re-usable on its own and de-coupled from the menu service, then the menu service is a switchboard receiving events from many input services and dispatching them to relevant output services.

what do you think? :smiley_cat:

**Comment by mycognosist** [comment]
hey @ahdinosaur, thanks!

i'm 100% onboard with your suggestion, good thinking! i haven't worked with the [jsonrpc pubsub module](https://github.com/paritytech/jsonrpc/tree/master/pubsub) yet but there are lots of examples to work from - shouldn't be too difficult to implement.

it's exciting to see the building blocks slowly coming together :sunflower:

**Comment by mycognosist** [comment]
@ahdinosaur i've implemented pubsub functionality in the [pubsub branch](https://github.com/peachcloud/peach-buttons/tree/pubsub) of `peach-buttons`. so far, so good.

i'll work on relevant changes to `peach-menu` in the coming days.
